apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: dynamic-claim
spec: 
  accessModes:
    - ReadWriteOnce
  storageClass: dynamic-storage
  resources:
    requests:
      storage: 6Gi

---
apiVersion: v1 
kind: Pod
metadata:
 name: dynamic-claim-pod
spec: 
 containers:
  - name: nginx 
    image: nginx 
    volumeMounts: 
      name: dynamic 
      mountPath: /usr/share/nginx/html 
    volumes: 
     - name: dynamic 
       PersistentVolumeClaim: 
         claimName: dynamic-claim