apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOncePod
  csi: 
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle:    #volume-id of the EBS which we created in the AWS 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  storageClassName: ""
  volumeName: static-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiversion: v1
kind: Pod 
metadata: 
 name: static-vol-pod
spec: 
  containers:
   - name: nginx
     image: nginx 
     volumeMounts: 
      - name: html-data 
        mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d       # This is for learning purpose, here we are telling k8s scheduler to schedule this pod on the node in us-east-1d as the ebs is present there
  volumes: 
   - name: html-data 
     PersistentVolumeClaim: 
       claimName: ebs-static

 